# Generated by Django 3.1 on 2023-07-12 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommoDityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(default=django.utils.timezone.now, verbose_name='上傳時間')),
                ('renew_time', models.DateField(default=django.utils.timezone.now, verbose_name='最後更新時間')),
                ('commo_type', models.CharField(max_length=50, verbose_name='種類')),
                ('seller', models.CharField(max_length=50, verbose_name='賣家')),
                ('rarity', models.CharField(max_length=50, verbose_name='稀有度')),
                ('commo_money', models.IntegerField(verbose_name='商品金額')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(default=django.utils.timezone.now, verbose_name='上傳時間')),
                ('renew_time', models.DateField(default=django.utils.timezone.now, verbose_name='最後更新時間')),
                ('message', models.CharField(max_length=255, verbose_name='留言板')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
