# Generated by Django 3.1 on 2023-07-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoditymodel',
            name='ability',
            field=models.CharField(choices=[('+1', '力量'), ('+2', '力量'), ('+3', '力量'), ('+4', '力量')], default='', max_length=50, verbose_name='能力'),
        ),
        migrations.AlterField(
            model_name='commoditymodel',
            name='commo_type',
            field=models.CharField(default='', max_length=50, verbose_name='種類'),
        ),
        migrations.AlterField(
            model_name='commoditymodel',
            name='rarity',
            field=models.CharField(default='', max_length=50, verbose_name='稀有度'),
        ),
        migrations.AlterField(
            model_name='commoditymodel',
            name='seller',
            field=models.CharField(default='', max_length=50, verbose_name='賣家'),
        ),
    ]
