# Generated by Django 3.1 on 2023-07-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20230731_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoditymodel',
            name='ability',
            field=models.CharField(choices=[('+1', '+1力量'), ('+2', '+2力量'), ('+3', '+3力量'), ('+4', '+4力量')], default='', max_length=50, verbose_name='能力'),
        ),
    ]
