# Generated by Django 3.1 on 2023-07-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20230731_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoditymodel',
            name='ability',
            field=models.CharField(default='', max_length=50, verbose_name='能力'),
        ),
        migrations.AlterField(
            model_name='commoditymodel',
            name='create_time',
            field=models.CharField(default='2023-07-30 18:11:56', max_length=50, verbose_name='上傳時間'),
        ),
        migrations.AlterField(
            model_name='commoditymodel',
            name='renew_time',
            field=models.CharField(default='2023-07-30 18:11:56', max_length=50, verbose_name='最後更新時間'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='create_time',
            field=models.CharField(default='2023-07-30 18:11:56', max_length=50, verbose_name='上傳時間'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='renew_time',
            field=models.CharField(default='2023-07-30 18:11:56', max_length=50, verbose_name='最後更新時間'),
        ),
    ]
